function player(id){
  this.name="Player "+(id+1);
  this.color="#FF0000";
  this.x=0;
  this.y=0;
  this.money=0;
  this.lives=5;
  this.health=3;
  this.id=id;
  this.move=false;
  if(id===0){
    this.upKey="keys.up";
    this.downKey="keys.down";
    this.leftKey="keys.left";
    this.rightKey="keys.right";
  }else if(id===1){
    this.upKey="keys.w";
    this.downKey="keys.s";
    this.leftKey="keys.a";
    this.rightKey="keys.d"
  }else if(id===2){
    this.upKey="keys.t";
    this.downKey="keys.g";
    this.leftKey="keys.f";
    this.rightKey="keys.h";
  }else if(id===3){
    this.upKey="keys.i";
    this.downKey="keys.k";
    this.leftKey="keys.j";
    this.rightKey="keys.l";
  }
  this.powerUps=[0,0,0,0,0,0,0];//high jump,dbl jump,flight,ex health,sheild,dbl coins,speed boost
  this.uC=0;
  this.draw=function(){
    ctx.fillStyle=this.color;
    ctx.fillRect(this.x,this.y,15,15);
    ctx.beginPath();
    ctx.arc(this.x+5,this.y+5,5,0,360);
    ctx.fillStyle="#FFFFFF";
    ctx.strokeStyle="#000000";
    ctx.lineWidth=0;
    ctx.fill();
    ctx.stroke();
    ctx.beginPath();
    if(this.move!==false){
      if(this.move==="left")
        ctx.arc(this.x+2,this.y+5,2,0,2*Math.PI);
      if(this.move==="right")
        ctx.arc(this.x+8,this.y+5,2,0,2*Math.PI);
      if(this.move==="up")
        ctx.arc(this.x+5,this.y+2,2,0,2*Math.PI);
      if(this.move==="down")
        ctx.arc(this.x+5,this.y+8,2,0,2*Math.PI);
    }else{
      ctx.arc(this.x+5,this.y+5,2,0,2*Math.PI);
    }
    ctx.fillStyle="#000000";
    ctx.fill();
    ctx.stroke();
  }
  this.left=function(){
    this.move="left";
    this.x--;
  }
  this.right=function(){
    this.move="right";
    this.x++;
  }
  this.up=function(){
    this.move="up";
    this.y--;
  }
  this.down=function(){
    this.move="down";
    this.y++;
  }
  this.stay=function(){
    this.move=false;
  }
}
